apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: init-deployment
  name: init-deployment
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: init-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: init-deployment
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: workdir
          mountPath: /usr/share/nginx/html
      initContainers:
      - name: pull-index-page
        image: busybox
        command:
        - wget
        - "-O"
        - "/work-dir/index.html"
        - https://raw.githubusercontent.com/salterje/testindexpage/master/index.html
        volumeMounts:
        - name: workdir
          mountPath: "/work-dir"
      - name: check-service
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup myservice.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for myservice; sleep 2; done"]
      volumes:
      - name: workdir
        emptyDir: {}
